<a href="https://colab.research.google.com/github/HarshitaSakhare29/Python1/blob/main/NUMPY.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#NUMPY package for multidimensional array

import numpy as np

In [ ]:
arr = np.array ([1,2,3,4,5,6])
arr

array([1, 2, 3, 4, 5, 6])

In [ ]:
lists_of_lists = [[1,2,3],[4,5,6],[7,8,9]]
sample_matrix = np.array(lists_of_lists)
sample_matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
np.arange(1,15)


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [ ]:
np.arange(20)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [ ]:
np.arange(1,46,5)

array([ 1,  6, 11, 16, 21, 26, 31, 36, 41])

In [ ]:
np.zeros(5)


array([0., 0., 0., 0., 0.])

In [ ]:
np.zeros(5,int)

array([0, 0, 0, 0, 0])

In [ ]:
np.zeros(10,dtype = int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [ ]:
np.zeros((2,5),int)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [ ]:
np.zeros((2,10),int)

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [ ]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [ ]:
np.linspace(0,20,8)

array([ 0.        ,  2.85714286,  5.71428571,  8.57142857, 11.42857143,
       14.28571429, 17.14285714, 20.        ])

In [ ]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
np.random.rand(3,2)

array([[0.67592508, 0.42563017],
       [0.16380708, 0.98562579],
       [0.12809175, 0.05291557]])

In [ ]:
np.random.randn(3,2)

array([[-0.91683347,  0.69481734],
       [-0.19136425, -0.43170891],
       [ 0.53746291,  0.27797355]])

In [ ]:
np.random.randint(1,5)

2

In [ ]:
np.random.randint(34,100,50)

array([92, 56, 78, 91, 71, 92, 92, 59, 42, 38, 77, 75, 78, 51, 60, 37, 95,
       53, 44, 60, 89, 42, 51, 38, 81, 88, 60, 36, 74, 78, 49, 70, 62, 72,
       49, 97, 78, 47, 47, 53, 66, 55, 74, 52, 86, 75, 90, 39, 36, 39])

In [ ]:
sample_array = np.arange(30)
sample_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [ ]:
rand_array = np.random.randint(0,100,20)
rand_array

array([34, 44, 21,  0, 66, 45, 88, 17, 12, 87, 24, 80, 24, 55, 81, 72,  2,
       11, 63, 39])

In [ ]:
sample_array.reshape(3,10)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [ ]:
rand_array.min()

0

In [ ]:
rand_array.argmin()

3

In [ ]:
a = np.eye(5)
a

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
a.T

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
a = np.random.rand(2,3)
a

array([[0.37907336, 0.53043049, 0.64264886],
       [0.52520538, 0.67923286, 0.93451614]])

In [ ]:
a.T

array([[0.37907336, 0.52520538],
       [0.53043049, 0.67923286],
       [0.64264886, 0.93451614]])

In [ ]:
sample_array = np.arange(10,21)
sample_array

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [ ]:
sample_array[3]

13

In [ ]:
##SLICEING

sample_array[3:7]

array([13, 14, 15, 16])

In [ ]:
sample_array[1:4]=100
sample_array

array([ 10, 100, 100, 100,  14,  15,  16,  17,  18,  19,  20])

In [ ]:
sample_array = np.arange(10,21)
sample_array

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [ ]:
sample_array[0:7]


array([10, 11, 12, 13, 14, 15, 16])

In [ ]:
subset_sample_array = sample_array[0:7]
subset_sample_array

array([10, 11, 12, 13, 14, 15, 16])

In [ ]:
###TWO-DIMENSIONAL ARRAY

sample_matrix = np.array([[50,20,1,23],[24,23,21,33],[56,76,24,7]])
sample_matrix

array([[50, 20,  1, 23],
       [24, 23, 21, 33],
       [56, 76, 24,  7]])

In [ ]:
sample_matrix[0:2,2]

array([ 1, 21])

In [ ]:
sample_matrix[2,:]

array([56, 76, 24,  7])

In [ ]:
sample_matrix[2]

array([56, 76, 24,  7])

In [ ]:
sample_matrix[:,(3,2)]

array([[23,  1],
       [33, 21],
       [ 7, 24]])

In [ ]:
sample_array = np.arange(1,20)
sample_array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [ ]:
sample_array+sample_array

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
       36, 38])

In [ ]:
np.exp(sample_array)

array([2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
       1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
       8.10308393e+03, 2.20264658e+04, 5.98741417e+04, 1.62754791e+05,
       4.42413392e+05, 1.20260428e+06, 3.26901737e+06, 8.88611052e+06,
       2.41549528e+07, 6.56599691e+07, 1.78482301e+08])

In [ ]:
np.sqrt(sample_array)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        , 3.16227766,
       3.31662479, 3.46410162, 3.60555128, 3.74165739, 3.87298335,
       4.        , 4.12310563, 4.24264069, 4.35889894])

In [ ]:
np.log(sample_array)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015, 2.07944154, 2.19722458, 2.30258509,
       2.39789527, 2.48490665, 2.56494936, 2.63905733, 2.7080502 ,
       2.77258872, 2.83321334, 2.89037176, 2.94443898])

In [ ]:
np.max(sample_array)

19

In [ ]:
np.min(sample_array)

1

In [ ]:
np.argmin(sample_array)

0

In [ ]:
np.square(sample_array)

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144, 169,
       196, 225, 256, 289, 324, 361])

In [ ]:
np.argmax(sample_array)

18

In [ ]:
np.std(sample_array)

5.477225575051661

In [ ]:
np.var(sample_array)

30.0

In [ ]:
np.mean(sample_array)

10.0

In [66]:
array = np.random.randn(3,4)
array

array([[-0.42685597, -1.35341404, -1.70810276, -0.22232467],
       [-0.70148715, -1.48475647, -0.52588005, -0.59457446],
       [-0.83436328,  1.56884686,  0.84462572, -0.24559684]])

In [67]:
np.round(array,decimals=3)

array([[-0.427, -1.353, -1.708, -0.222],
       [-0.701, -1.485, -0.526, -0.595],
       [-0.834,  1.569,  0.845, -0.246]])

In [68]:
sports = np. array (['golf','fball','cricket','cricket','basketball'])
np.unique(sports)

array(['basketball', 'cricket', 'fball', 'golf'], dtype='<U10')